#!/usr/bin/env bash
# Setup Log Rotation for Solr v2.5.0
# Configures logrotate for Solr application logs in Docker environment

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load common library
# shellcheck source=scripts/lib/common.sh
source "$SCRIPT_DIR/lib/common.sh" || {
    echo "Error: Failed to load common.sh library"
    exit 1
}

setup_error_handling

# ============================================================================
# CONFIGURATION
# ============================================================================

LOG_DIR="${SOLR_LOG_DIR:-/var/solr/logs}"
ROTATE_DAYS="${LOG_ROTATE_DAYS:-14}"
MAX_SIZE="${LOG_MAX_SIZE:-100M}"
COMPRESS="${LOG_COMPRESS:-true}"

log_info "Setting up log rotation for Solr logs"
log_info "Log directory: $LOG_DIR"
log_info "Retention: $ROTATE_DAYS days"
log_info "Max size: $MAX_SIZE"

# ============================================================================
# LOGROTATE CONFIGURATION
# ============================================================================

# Create logrotate config
cat > /tmp/solr-logrotate.conf <<EOF
# Solr Log Rotation Configuration v2.5.0
# Auto-generated by setup-log-rotation.sh

$LOG_DIR/*.log {
    # Rotate daily
    daily

    # Keep logs for N days
    rotate $ROTATE_DAYS

    # Compress rotated logs (except most recent)
    compress
    delaycompress

    # Don't error if log is missing
    missingok

    # Don't rotate empty logs
    notifempty

    # Copy and truncate instead of moving (Solr keeps file handle open)
    copytruncate

    # Maximum size before rotation (regardless of time)
    maxsize $MAX_SIZE

    # Don't mail logs
    nomail

    # Create new log files with correct permissions
    create 0644 8983 8983

    # Date extension format
    dateext
    dateformat -%Y%m%d-%s

    # Post-rotation script (optional)
    postrotate
        # Optional: Send notification or cleanup
        echo "Solr logs rotated at \$(date)" >> $LOG_DIR/rotation.log || true
    endscript
}

# GC logs (if enabled)
$LOG_DIR/gc*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    maxsize 50M
    create 0644 8983 8983
    dateext
}

# Rotation log itself
$LOG_DIR/rotation.log {
    weekly
    rotate 4
    compress
    missingok
    notifempty
    copytruncate
    maxsize 10M
}
EOF

log_success "Logrotate configuration created"
cat /tmp/solr-logrotate.conf

# ============================================================================
# INSTALL LOGROTATE (if not already installed)
# ============================================================================

if ! command -v logrotate &>/dev/null; then
    log_info "Installing logrotate..."

    # Detect OS and install
    if command -v apk &>/dev/null; then
        # Alpine
        apk add --no-cache logrotate
    elif command -v apt-get &>/dev/null; then
        # Debian/Ubuntu
        apt-get update && apt-get install -y logrotate
    elif command -v yum &>/dev/null; then
        # RHEL/CentOS
        yum install -y logrotate
    else
        log_error "Unable to install logrotate (unknown OS)"
        exit 1
    fi

    log_success "Logrotate installed"
else
    log_success "Logrotate already installed"
fi

# ============================================================================
# CREATE CRON JOB
# ============================================================================

log_info "Setting up cron job for log rotation..."

# Create cron entry (run daily at 2 AM)
cat > /tmp/solr-logrotate-cron <<'EOF'
# Solr Log Rotation - Run daily at 2:00 AM
0 2 * * * /usr/sbin/logrotate -s /var/solr/logs/logrotate.status /tmp/solr-logrotate.conf 2>&1 | logger -t solr-logrotate
EOF

log_success "Cron configuration created"
cat /tmp/solr-logrotate-cron

# ============================================================================
# MANUAL EXECUTION
# ============================================================================

log_info "Testing log rotation (dry run)..."

if logrotate -d /tmp/solr-logrotate.conf; then
    log_success "Log rotation configuration is valid"
else
    log_error "Log rotation configuration has errors"
    exit 1
fi

log_success "Log rotation setup complete!"
echo ""
echo "Configuration files created:"
echo "  - /tmp/solr-logrotate.conf (logrotate config)"
echo "  - /tmp/solr-logrotate-cron (cron entry)"
echo ""
echo "To enable log rotation, add these to your container:"
echo "  1. Copy logrotate.conf to container"
echo "  2. Install logrotate package"
echo "  3. Add cron entry or run as systemd timer"
echo ""
echo "Manual execution:"
echo "  logrotate -f /tmp/solr-logrotate.conf"
